### ISSUE TITLE
[QUESTION] How to Change the Database to MongoDB

### ISSUE THREAD

**Issue by thisisash1** [NullDev/Discord-RoleShop#38]
Hello! I want to change the currently connected database to my MongoDB database. Could you please tell me how to do that? Thank you!

**Comment by NullDev** [comment]
Changing the database system just like that can't be done without rewriting all of the code that performs database actions. The current code is laid out for QuickDB and won't be able to just interact with another Database. I am not planning on supporting any more/other Database systems because it would require a major rewrite of most of the code as well as implementing data migrations between databases.
